***
# <font color=brown size=10>CURSO DE ESTATÍSTICA - SETOR ENERGIA</font>
***

# <font color=brown>1 ENTENDA OS DADOS</font>
***

## <font color=brown>1.1 Dataset do projeto</font>
***

### Atos de outorga a partir de 2015

A base de dados dos <b>Atos de Outorga</b> contém os dados de expedição de atos de outorgas de usinas do setor elétrico a partir do ano de 2015. O levantamento dessas estatísticas constitui um importante instrumento para avaliação da expectativa de oferta de energia futura, bem como os possíveis efeitos oriundos de políticas públicas e regulamentações no que tangem a geração de energia.

### Fonte dos Dados

https://dadosabertos.aneel.gov.br/dataset/atos-de-outorgas-de-geracao

### Variáveis utilizadas

> ### Data de publicação do ato
> ***

A data em que foi publicada o ato no formato XX/XX/XXXX.

> ### UF
> ***

|Código|Descrição|
|---|---|
|11|SP|
|12|MG|
|13|PE|
|14|RS|
|15|GO|
|16|MA|
|17|MT|
|21|AC|
|22|AL|
|23|AM|
|24|AP|
|25|BA|
|26|CE|
|27|DF|
|28|ES|
|29|MS|
|31|PA|
|32|PB|
|33|PR|
|35|PI|
|41|RJ|
|42|RN|
|43|RO|
|50|RR|
|51|SC|
|52|SE|
|53|SP|
|54|TO|

> ### Ambiente comercialização
> ***

|Código|Descrição|
|---|---|
|1|ACL|
|2|ACR|

> ### Fontes de geração
> ***

> Abreviação do tipo de geração. Classificado em:
> 1. UTN - Usina Termonuclear;
> 2. UTE - Usina Termelétrica;
> 3. UHE - Usina Hidrelétrica;
> 4. UFV - Central Geradora Solar Fotovoltaica;
> 5. PCH - Pequena Central Hidrelétrica;
> 6. EOL - Central Geradora Eólica

|Código|Descrição|
|---|---|
|0|UFV|
|1|EOL|
|2|UTE|
|3|UTN|
|4|PCH|
|6|CGH|
|7|UHE|

#### <font color='red'>Observação</font>
***
> Os seguintes tratamentos foram realizados nos dados originais:
> 1. Foram eliminadas as colunas que não era do interesse da análise;
> 2. Foram renomeadas as colunas para melhor compreensão do dado;

## Importando bibliotecas do projeto e leitura de arquivo externo

https://pandas.pydata.org/

In [ ]:
#importação bibliotecas

In [ ]:
#leitura arquivo externo

## Tratamento da base de dados

In [ ]:
#Exclusão colunas

In [ ]:
#Renomeação de colunas

In [ ]:
# Substituindo os valores na coluna "Ambiente de comercialização"

In [ ]:
# Convertendo a coluna "DatPublicacao" para o tipo datetime

In [ ]:
# Criando a coluna "Ano" com o ano extraído da coluna "DatPublicacao"

In [ ]:
# Reordenando ordem colunas

Visualização do dataframe

In [ ]:
#visualização dataframe

Informação base de dados

In [ ]:
#informação base de dados

## <font color=brown>1.2 Tipos de dados</font>
***

### Classificação de uma variável
<img src='https://upload.wikimedia.org/wikipedia/commons/e/e4/Tipos_de_dados.png' width='70%'>

### Variáveis qualitativas ordinais

► Variáveis que podem ser ordenadas ou hierarquizardas

### Variáveis qualitativas nominais

► Variáveis que não podem ser ordenadas ou hierarquizardas

### Variáveis quantitativas discretas

► Variáveis que representam uma contagem onde os valores possíveis formam um conjunto finito ou enumerável.

### Variáveis quantitativas contínuas

► Variáveis que representam uma contagem ou mensuração que assumem valores em uma escala contínua (números reais).

# <font color=brown>2 START DO SEU PROJETO </font>
***

> Realize os seguintes passos para realizar sua análise de dados:
> 1. Defina objetivo da análise: para o nosso caso, estamos em busca em  compreender a  evolução das outorgas de geração.  
> 2. Estruture a lógica de programação:

              *   importação da base de dados
              *   compreensão dos dados disponíveis
              *   tratamento da base de dados
              *   técnicas estatísticas


> 3. Conclusões: nesse momento você entenderá o comportamento dos seus dados e, com isso, relacioná-los com informações pertinentes a fim de compreender os resultados e tirar conclusões.

# <font color=brown>3 TÉCNICAS ESTÁTISTICAS - DISTRIBUIÇÃO DE FREQUÊNCIAS</font>
***

O conhecimento do comportamento das variáveis envolvidas na análise é fundamental. Para isso, existe a técnica estatística chamada análises das <b>DISTRIBUIÇÕES DE FREQUÊNCIAS</b> e <b>HISTOGRAMAS</b> em que podemos avaliar melhor a forma como os fenômenos em estudo se distribuem.

#### <font color='red'>Observação</font>
***

Séries temporais são um conjunto de observações de **uma mesma variável quantitativa (discreta ou contínua)** feitas ao longo do tempo.

Por exemplo, um conjunto de temperaturas medidas diariamente numa região.

## <font color=brown>3.1 Distribuição de frequências para variáveis qualitativas</font>
***

### Método 1

https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.Series.value_counts.html

In [ ]:
#cálculo da frequência absoluta fontes de geração

In [ ]:
#cálculo da frequência relativa fontes de geração

In [ ]:
#criação da tabela de frequências

In [ ]:
#visualização da tabela

In [ ]:
#criação gráfico de barras

In [ ]:
#cálculo da frequência absoluta anos de emissão

In [ ]:
#cálculo da frequência relativa anos de emissão

In [ ]:
#criação da tabela de frequências

In [ ]:
# Resetando o índice e movendo os valores de 'Ano' para uma coluna separada

In [ ]:
# Definindo os dados do gráfico de pizza
labels = dist_freq_quantitativas['Ano']
sizes = dist_freq_quantitativas['Porcentagem (%)']

# Criando a figura e o subplot
fig, ax = plt.subplots(figsize=(8, 8))

# Criando o gráfico de pizza
ax.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140)
ax.set_title('Distribuição de Porcentagem por Ano', pad=20)  # Adicionando um espaço extra entre o título e o gráfico.

# Ajustando o aspecto do gráfico para ficar como um círculo
ax.axis('equal')

# Exibindo o gráfico
plt.show()

In [ ]:
# Criar o gráfico

fig, ax = plt.subplots(figsize=(10, 6))
ax.bar(dist_freq_quantitativas['Ano'], dist_freq_quantitativas['Frequência'], color='blue', label='Frequência')
ax.set_xlabel('Ano')
ax.set_ylabel('Frequência')
ax.set_title('Frequência ao longo dos anos')
ax.legend()

# Adicionar uma segunda escala no eixo y para a porcentagem
ax2 = ax.twinx()
ax2.plot(dist_freq_quantitativas['Ano'], dist_freq_quantitativas['Porcentagem (%)'], color='red', marker='o', label='Porcentagem (%)')
ax2.set_ylabel('Porcentagem (%)')
ax2.legend(loc='upper right')

# Configurar os valores dos ticks no eixo x para mostrar todos os anos
ax.set_xticks(dist_freq_quantitativas['Ano'])

# Mostrar o gráfico
plt.show()

In [ ]:
ano_fontes = final_df.groupby(['Ano', 'Fonte Geração']).size().unstack(fill_value=0)

ano_fontes = ano_fontes.reset_index()

ano_fontes

In [ ]:
# Crie o gráfico de barras
fig = px.bar(ano_fontes, x='Ano', y=['CGH', 'EOL', 'PCH', 'UFV', 'UHE', 'UTE', 'UTN'],
             labels={'value': 'Contagem'})

# Adicione um título ao gráfico
fig.update_layout(title_text='Quantidade de Fontes de Geração por Ano', title_x=0.5)

# Mostrar o gráfico
fig.show()

In [ ]:
ano_ambiente = final_df.groupby(['Ano', 'Ambiente comercialização']).size().unstack(fill_value=0)

ano_ambiente.sort_index(ascending = False)

ano_ambiente

In [ ]:
cores = ['blue', 'purple']

grafico_ano_ambiente = ano_ambiente.plot.bar(width=0.8, color=cores, alpha=0.2, figsize=(14, 6))

grafico_ano_ambiente

### Método 2

https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.crosstab.html

In [ ]:
#dicionário das variáveis

fontes = {
    0: 'UFV',
    1: 'EOL',
    2: 'UTE',
    3: 'UTN',
    4: 'PCH',
    6: 'CGH',
    7: 'UHE'
}


uf = {
    11: 'SP',
    12: 'MG',
    13: 'PE',
    14: 'RS',
    15: 'GO',
    16: 'MA',
    17: 'MT',
    21: 'AC',
    22: 'AL',
    23: 'AM',
    24: 'AP',
    25: 'BA',
    26: 'CE',
    27: 'DF',
    28: 'ES',
    29: 'MS',
    31: 'PA',
    32: 'PB',
    33: 'PR',
    35: 'PI',
    41: 'RJ',
    42: 'RN',
    43: 'RO',
    50: 'RR',
    51: 'SC',
    52: 'SE',
    53: 'SP',
    54: 'TO'
}

ambiente = {
    1: 'ACL',
    2: 'ACR',
}

In [ ]:
frequencia_brasil = pd.crosstab(final_df['Fonte Geração'],
                         final_df['UF']
                        )
frequencia_brasil.rename(index = fontes, inplace = True)
frequencia_brasil.rename(columns = uf, inplace = True)
frequencia_brasil

UF,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
Fonte Geração,,,,,,,,,,,,,,,,,,,,,
CGH,0,0,0,0,0,0,0,6,1,0,...,4,3,0,0,0,1,24,0,5,9
EOL,0,4,0,0,6388,1621,0,0,0,282,...,215,3,4072,0,0,1678,33,41,1,0
PCH,0,8,19,5,57,6,2,63,372,22,...,596,137,7,30,0,316,467,0,160,50
UFV,0,150,1,0,4529,2272,1,0,722,62,...,7,29,2024,6,0,5,1,71,490,279
UHE,0,2,1,10,25,0,1,12,47,6,...,66,15,0,4,1,55,64,2,72,13
UTE,44,13,570,18,115,54,2,63,86,50,...,73,211,16,99,44,72,70,78,483,5
UTN,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

> Sintaxe da função:
> 1. frequencia_brasil - variável armazenária a tabela
> 2. pd.crosstab(final_df['Fonte Geração'], final_df['UF']) - esta parte utiliza a função pd.crosstab() para criar uma tabela de contingência (crosstab) que contém a contagem de ocorrências das diferentes fontes de geração em relação aos estados (UF) presentes no DataFrame final_df. Os valores únicos na coluna "Fonte Geração" se tornam as linhas da tabela, e os valores únicos na coluna "UF" se tornam as colunas.

In [ ]:
percentual_brasil = pd.crosstab(final_df['Fonte Geração'],
                         final_df['UF'],
                         normalize = True
                        ) * 100
percentual_brasil.rename(index = fontes, inplace = True)
percentual_brasil.rename(columns = uf, inplace = True)
percentual_brasil

UF,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
Fonte Geração,,,,,,,,,,,,,,,,,,,,,
CGH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013315,0.002219,0.000000,...,0.008877,0.006658,0.000000,0.000000,0.000000,0.002219,0.053261,0.000000,0.011096,0.019973
EOL,0.000000,0.008877,0.000000,0.000000,14.176339,3.597346,0.000000,0.000000,0.000000,0.625818,...,0.477131,0.006658,9.036639,0.000000,0.000000,3.723841,0.073234,0.090988,0.002219,0.000000
PCH,0.000000,0.017754,0.042165,0.011096,0.126495,0.013315,0.004438,0.139810,0.825548,0.048823,...,1.322652,0.304032,0.015534,0.066576,0.000000,0.701272,1.036373,0.000000,0.355074,0.110961
UFV,0.000000,0.332882,0.002219,0.000000,10.050820,5.042054,0.002219,0.000000,1.602272,0.137591,...,0.015534,0.064357,4.491689,0.013315,0.000000,0.011096,0.002219,0.157564,1.087415,0.619161
UHE,0.000000,0.004438,0.002219,0.022192,0.055480,0.000000,0.002219,0.026631,0.104303,0.013315,...,0.146468,0.033288,0.000000,0.008877,0.002219,0.122057,0.142030,0.004438,0.159783,0.028850
UTE,0.097645,0.028850,1.264952,0.039946,0.255210,0.119838,0.004438,0.139810,0.190852,0.110961,...,0.162003,0.468254,0.035507,0.219702,0.097645,0.159783,0.155345,0.173099,1.071880,0.011096
UTN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.002219,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
frequencia_ambientcomerc = pd.crosstab(final_df['Fonte Geração'],
                         final_df['Ambiente comercialização']
                        )
frequencia_ambientcomerc.rename(index = fontes, inplace = True)
frequencia_ambientcomerc.rename(columns = ambiente, inplace = True)
frequencia_ambientcomerc

Ambiente comercialização    ACL    ACR
Fonte Geração
CGH                          63     37
EOL                        6628  10946
PCH                        3339    136
UFV                       14849   6873
UHE                         773     92
UTE                        1964    946
UTN                           0      1

In [ ]:
percentual_ambientcomerc = pd.crosstab(final_df['Fonte Geração'],
                         final_df['Ambiente comercialização'],
                         normalize = True
                        ) * 100
percentual_brasil.rename(index = fontes, inplace = True)
percentual_brasil.rename(columns = ambiente, inplace = True)
percentual_brasil

UF,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
Fonte Geração,,,,,,,,,,,,,,,,,,,,,
CGH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013315,0.002219,0.000000,...,0.008877,0.006658,0.000000,0.000000,0.000000,0.002219,0.053261,0.000000,0.011096,0.019973
EOL,0.000000,0.008877,0.000000,0.000000,14.176339,3.597346,0.000000,0.000000,0.000000,0.625818,...,0.477131,0.006658,9.036639,0.000000,0.000000,3.723841,0.073234,0.090988,0.002219,0.000000
PCH,0.000000,0.017754,0.042165,0.011096,0.126495,0.013315,0.004438,0.139810,0.825548,0.048823,...,1.322652,0.304032,0.015534,0.066576,0.000000,0.701272,1.036373,0.000000,0.355074,0.110961
UFV,0.000000,0.332882,0.002219,0.000000,10.050820,5.042054,0.002219,0.000000,1.602272,0.137591,...,0.015534,0.064357,4.491689,0.013315,0.000000,0.011096,0.002219,0.157564,1.087415,0.619161
UHE,0.000000,0.004438,0.002219,0.022192,0.055480,0.000000,0.002219,0.026631,0.104303,0.013315,...,0.146468,0.033288,0.000000,0.008877,0.002219,0.122057,0.142030,0.004438,0.159783,0.028850
UTE,0.097645,0.028850,1.264952,0.039946,0.255210,0.119838,0.004438,0.139810,0.190852,0.110961,...,0.162003,0.468254,0.035507,0.219702,0.097645,0.159783,0.155345,0.173099,1.071880,0.011096
UTN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.002219,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000